# -*- coding: utf-8 -*-
"""embeddingword.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brLLlPDwYfLiKEYl6EMWqwq_Wegeh-0a
"""

import pandas as pd
import io
from gensim.test.utils import common_texts
from gensim.models import Word2Vec

#import file csv for study
from google.colab import files
uploaded = files.upload()

#read file 
df = pd.read_csv(io.StringIO(uploaded['data.csv'].decode('utf-8')))
#print file upload
df

df['Maker_Model']= df['Make']+ " " + df['Model']

##generetad format list
df1 = df[['Engine Fuel Type','Transmission Type','Driven_Wheels',
          'Market Category','Vehicle Size', 'Vehicle Style', 'Maker_Model']]

##cada linha combina todas as colunas em uma coluna só
df2 = df1.apply(lambda x: ','.join(x.astype(str)), axis=1)
##armazena em um dataframe pandas
df_clean = pd.DataFrame({'clean': df2})
## cria a lista do formato lista  do corpus personalizado para a modelagem gesim
sent = [row.split(',') for row in df_clean['clean']]

##mostra o exemplo da lista do formato lista  do corpus modelado para a modelagem de gesim
sent[:2]

##treinar o modelo gensin word2vec com o corpus personalizado da seguinte maneira
model = Word2Vec(sent, min_count=1,size= 50,workers=3, window =3, sg = 1)

##modelo treinado
model['BMW 3 Series']